import React from 'react'

function Background() {
  return (
    <>
      <div class="background">
      </div>
      <div class="scroll-wrapper">
        <div class="scroll scroll1">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll2" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll3" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll4">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll1">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll2">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll4">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll1" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll3" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll4">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll2" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll1" >
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
        <div class="scroll scroll4">
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
          <div>
            <span>HTML</span>
            <span>CSS</span>
            <span>JAVASCRIPT</span>
            <span>REACTJS</span>
            <span>LARAVEL</span>
            <span>REACTNATIVE</span>
            <span>PHP</span>
            <span>NEXTJS</span>
            <span>MYSQL</span>
            <span>VITE</span>
            <span>NODEJS</span>
          </div>
        </div>
      </div>

    </>

  )
}


export default Background